using Nutzen;
using Nutzen.Common;
using Nutzen.Common.Logging;
using Nutzen.Common.MemoryCache;
using Nutzen.Common.Retry;
using Scalar.AspNetCore;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

// Register all generated handlers (generated by the ServiceRegistrationGenerator)
// The method name follows the pattern: AddNutzenFrom{AssemblyNameWithoutNutzenPrefix}
builder.Services
    .AddNutzen()
    .AddNutzenCommon()
    .AddNutzenFromWebAPI();

// Add Memory Cache Interceptor with default options
builder.Services.AddMemoryCacheInterceptor(options =>
{
    options.DefaultAbsoluteExpiration = TimeSpan.FromSeconds(5);
    options.CleanupInterval = TimeSpan.FromSeconds(10);
});

// Add Retry Interceptor with configuration for handling exceptions
builder.Services.AddRetryInterceptor(options =>
{
    options.MaxRetryCount = 10;
    options.BaseDelay = TimeSpan.FromMilliseconds(200);
    options.UseExponentialBackoff = true;
    options.MaxJitter = TimeSpan.FromMilliseconds(50);
    options.ShouldRetryOnException = ex => ex is InvalidOperationException;
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.MapScalarApiReference(options =>
    {
        options.Title = "Nutzen WebAPI";
        options.Theme = ScalarTheme.DeepSpace;
    });
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
